export const productImageMapping = {
  Apples: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg',
  Bananas: 'https://images.pexels.com/photos/61127/pexels-photo-61127.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  'T-shirt': 'https://images.pexels.com/photos/833185/pexels-photo-833185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Jeans: 'https://images.pexels.com/photos/2068349/pexels-photo-2068349.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Laptop: 'https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Milk: 'https://images.pexels.com/photos/5996524/pexels-photo-5996524.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Eggs: 'https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Dress: 'https://images.pexels.com/photos/833185/pexels-photo-833185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Sneakers: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  Smartphone: 'https://images.pexels.com/photos/1294886/pexels-photo-1294886.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  'Orange Juice': 'https://upload.wikimedia.org/wikipedia/commons/0/05/Orangejuice.jpg',
  Broccoli: 'https://hips.hearstapps.com/hmg-prod/images/full-frame-shot-of-broccoli-royalty-free-image-571248799-1532377854.jpg?crop=0.752xw:1.00xh;0.141xw,0&resize=1200:*',
  Sweater: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTWGtatnpdNghmN1PBo8VZjSvw2XNZL6ubZw&s',
  Jacket: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0GAlY1BqA5ehxFxLWKAKFyvmX7AwOCVbfbg&s',
  Tablet: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSd09xcuiCXhudkgt1wsH8VKMcuXzCxe84cg&s',
  Bread: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuh6GS3uRlikeCkjT9t_eLW2v0yy2yGk1rrQ&s',
  Cheese: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAgilvLdshYzB7n-QLPIbBW78VoEVyba1pWg&s',
  Hat: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT47Ux031h1Yd7_umNPOJ0RgeEvEClqS1Jg5w&s',
  Socks: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEYmSNqtib6i-r8Kge_DDiICJIL64d3VljCg&s',
  Headphones: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcD6kVRb4fnx3B7V_D-8mOPdNzkLJUf4z68Q&s',
  Grapes: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNO9vexWQc4FMuoT4ACXoK_Hb2mtJZpmhiMw&s',
  Carrots: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8Ux38xjvxJLtXTpZ5q7VLPEodUfSH1G7SVQ&s',
  Skirt: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCOTEPsdwhetEygxz__IitYKSUViYGEMrYAg&s',
  Blouse: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxTjG4UM2vWeUU_5G3MQ6k7peich1axJ4DrobMM4lQLFKbPv0tXbV7J4mOgOF0WfpdQ-g&usqp=CAU',
  Camera: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqsFlMLk0pbqO0I1qLGm9bNVNxyqqZW2wuqQ&s',
  Tomatoes: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuv25Xs04SNJ0u8tpPspdLpJVp-Pqa1_6eVw&s',
  Cucumber: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Inw2iTIpC0XAEC0UT5-i2Hlp65Ibsa1CQQ&s',
  'Jeans Jacket': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi91v-U0YEDaqoQ0YSV7lJt2kTrBFnBIro8g&s',
  Scarf: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMMVJxHGrxE16qQF-OkirszIysxiqjxBCsMQ&s',
  Monitor: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSexneJdNaR9UxLkJsXa0EsWdSw2sHmesK5tw&s',
  Cereal: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuRN9ieG8UBj3_njvKkPqkorkgnxql722ebQ&s',
  Yogurt: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQPfbWZptyaMvlrP4KP4mgR5sjrd7aT6fhpg&s',
  Pants: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ-wFIv-TwTE2UsyMDQB-Z8uVLMPkp9V5tnQ&s',
  Jumpsuit: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm7-KSF3D-2Tyh0cbTZl6F0QqvZEHDO8oyBw&s',
  Smartwatch: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxFtk87-Q53bPpu4alzBxV3HKM6z8fu0Nexg&s',
  Peaches: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw5mZmHCNr3wKesmiAmn19GXmCtlxPkirGgw&s',
  Lettuce: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmCNWtMWGTPdxB3Y2hf88780eqm9YVPnKRow&s',
  Sweatshirt: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg3YcTrWKh8Uvcy79yIA_rSy9z1nRZKn9JlA&s',
  Belt: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmyg03rMANhhZQ1BYUqDxHm3kcL3iBdwXwRg&s',
  Keyboard: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH9DdVaqSvFpKBO7r5Zt4RLZGI35jI6-FTcA&s',
  Oranges: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTGUocwXZTxLr5D-jA1hC70DiNd2JlE7Vzfw&s',
  "Potatoes": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSloBWMjwgrjh_5ovqftgkeP1mEmeDzv0BfbQ&s",
  "Blazer": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAx8QHviDmCPrHy6bRuWMmtIsALCF-X7EfuA&s",
  "Gloves": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCQJnPlg-eElGG2gNtj1az1JJ795GmvxF6FA&s",
  "Router": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFC4i2q3N6mv2hokac144E3SADemqsYbL28A&s",
  "Watermelon": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWqpws4dnI740UCiKjjeGLKQkascFX8udy7w&s",
  "Pepper": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5ljsKYXt-s1sywOydx9vw16wnC4ldi1G8Mw&s",
  "Coat": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjkTlD45wCH9cmCSPsiBqjh9Na5xsZcE_2Bg&s",
  "Tie": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwFr6NUTFSGd2W-T9mAWtA0SZr7JjzKZmvew&s",
  "Laptop Stand": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIIwaNPHkU3GoPa5K33rdCsDH1n228PqFBSw&s"

};
